---
- name: This is a hello-world example
  hosts: all
  tasks:
  - name: Wait for ssh to be available
    wait_for_connection:
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy: 
      content: "hello world\n" 
      dest: /tmp/testfile.txt